# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 21:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre de la cuenta')),
                ('balance', models.FloatField(verbose_name='Balance')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Algorithm',
                'verbose_name_plural': 'Algorithms',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('income', models.FloatField(verbose_name='Ganancia')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
            },
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField(verbose_name='N\xfamero de cuenta')),
                ('percentage', models.IntegerField(verbose_name='Porcentaje de distribuci\xf3n')),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='saver.Algorithm', verbose_name='Algoritmo de ahorro')),
            ],
            options={
                'verbose_name': 'Distribution',
                'verbose_name_plural': 'Distributions',
            },
        ),
        migrations.CreateModel(
            name='Liability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('cost', models.FloatField(verbose_name='Costo')),
            ],
            options={
                'verbose_name': 'Liability',
                'verbose_name_plural': 'Liabilities',
            },
        ),
        migrations.CreateModel(
            name='Saver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savers', to='saver.Algorithm', verbose_name='Algoritmo de ahorro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savers', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Saver',
                'verbose_name_plural': 'Savers',
            },
        ),
        migrations.AddField(
            model_name='liability',
            name='saver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liabilities', to='saver.Saver', verbose_name='Ahorrador'),
        ),
        migrations.AddField(
            model_name='asset',
            name='saver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='saver.Saver', verbose_name='Ahorrador'),
        ),
        migrations.AddField(
            model_name='account',
            name='saver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='saver.Saver', verbose_name='Ahorrador'),
        ),
    ]
